// Generated by gencpp from file smartenv/detection.msg
// DO NOT EDIT!


#ifndef SMARTENV_MESSAGE_DETECTION_H
#define SMARTENV_MESSAGE_DETECTION_H

#include <ros/service_traits.h>


#include <smartenv/detectionRequest.h>
#include <smartenv/detectionResponse.h>


namespace smartenv
{

struct detection
{

typedef detectionRequest Request;
typedef detectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detection
} // namespace smartenv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smartenv::detection > {
  static const char* value()
  {
    return "bf8939a53b44d15d1f388142bf4233b3";
  }

  static const char* value(const ::smartenv::detection&) { return value(); }
};

template<>
struct DataType< ::smartenv::detection > {
  static const char* value()
  {
    return "smartenv/detection";
  }

  static const char* value(const ::smartenv::detection&) { return value(); }
};


// service_traits::MD5Sum< ::smartenv::detectionRequest> should match 
// service_traits::MD5Sum< ::smartenv::detection > 
template<>
struct MD5Sum< ::smartenv::detectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smartenv::detection >::value();
  }
  static const char* value(const ::smartenv::detectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartenv::detectionRequest> should match 
// service_traits::DataType< ::smartenv::detection > 
template<>
struct DataType< ::smartenv::detectionRequest>
{
  static const char* value()
  {
    return DataType< ::smartenv::detection >::value();
  }
  static const char* value(const ::smartenv::detectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smartenv::detectionResponse> should match 
// service_traits::MD5Sum< ::smartenv::detection > 
template<>
struct MD5Sum< ::smartenv::detectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smartenv::detection >::value();
  }
  static const char* value(const ::smartenv::detectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartenv::detectionResponse> should match 
// service_traits::DataType< ::smartenv::detection > 
template<>
struct DataType< ::smartenv::detectionResponse>
{
  static const char* value()
  {
    return DataType< ::smartenv::detection >::value();
  }
  static const char* value(const ::smartenv::detectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTENV_MESSAGE_DETECTION_H
