// Generated by gencpp from file smartenv/detectionResponse.msg
// DO NOT EDIT!


#ifndef SMARTENV_MESSAGE_DETECTIONRESPONSE_H
#define SMARTENV_MESSAGE_DETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smartenv
{
template <class ContainerAllocator>
struct detectionResponse_
{
  typedef detectionResponse_<ContainerAllocator> Type;

  detectionResponse_()
    : objects()  {
    }
  detectionResponse_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::smartenv::detectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartenv::detectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct detectionResponse_

typedef ::smartenv::detectionResponse_<std::allocator<void> > detectionResponse;

typedef boost::shared_ptr< ::smartenv::detectionResponse > detectionResponsePtr;
typedef boost::shared_ptr< ::smartenv::detectionResponse const> detectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartenv::detectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartenv::detectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace smartenv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::smartenv::detectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartenv::detectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartenv::detectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartenv::detectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartenv::detectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartenv::detectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartenv::detectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39d6292ea712a13252ebdb5470ba0086";
  }

  static const char* value(const ::smartenv::detectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39d6292ea712a132ULL;
  static const uint64_t static_value2 = 0x52ebdb5470ba0086ULL;
};

template<class ContainerAllocator>
struct DataType< ::smartenv::detectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartenv/detectionResponse";
  }

  static const char* value(const ::smartenv::detectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartenv::detectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] objects\n"
"\n"
;
  }

  static const char* value(const ::smartenv::detectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartenv::detectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartenv::detectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartenv::detectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTENV_MESSAGE_DETECTIONRESPONSE_H
