// Generated by gencpp from file smartenv/detectionRequest.msg
// DO NOT EDIT!


#ifndef SMARTENV_MESSAGE_DETECTIONREQUEST_H
#define SMARTENV_MESSAGE_DETECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smartenv
{
template <class ContainerAllocator>
struct detectionRequest_
{
  typedef detectionRequest_<ContainerAllocator> Type;

  detectionRequest_()
    : tag_format()
    , tag_id(0)  {
    }
  detectionRequest_(const ContainerAllocator& _alloc)
    : tag_format(_alloc)
    , tag_id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tag_format_type;
  _tag_format_type tag_format;

   typedef int16_t _tag_id_type;
  _tag_id_type tag_id;





  typedef boost::shared_ptr< ::smartenv::detectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartenv::detectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct detectionRequest_

typedef ::smartenv::detectionRequest_<std::allocator<void> > detectionRequest;

typedef boost::shared_ptr< ::smartenv::detectionRequest > detectionRequestPtr;
typedef boost::shared_ptr< ::smartenv::detectionRequest const> detectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartenv::detectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartenv::detectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace smartenv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::smartenv::detectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartenv::detectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartenv::detectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartenv::detectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartenv::detectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartenv::detectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartenv::detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71f447056ec542b35be2048c23f5b7c";
  }

  static const char* value(const ::smartenv::detectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71f447056ec542bULL;
  static const uint64_t static_value2 = 0x35be2048c23f5b7cULL;
};

template<class ContainerAllocator>
struct DataType< ::smartenv::detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartenv/detectionRequest";
  }

  static const char* value(const ::smartenv::detectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartenv::detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tag_format\n"
"int16 tag_id\n"
;
  }

  static const char* value(const ::smartenv::detectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartenv::detectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_format);
      stream.next(m.tag_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartenv::detectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartenv::detectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag_format: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tag_format);
    s << indent << "tag_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.tag_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTENV_MESSAGE_DETECTIONREQUEST_H
